name: prs
channels:
  - conda-forge
dependencies:
  - conda-forge::numpy=1.18.1
  - conda-forge::pandas=1.0.1
  - conda-forge::pip=19.3.1
  - conda-forge::python=3.8.1
  - conda-forge::scikit-learn=0.22.1
  - conda-forge::scikit-allel=1.2.1
  - conda-forge::scipy=1.4.1
  - conda-forge::statsmodels=0.10.1
  - conda-forge::tqdm=4.31.1
  - conda-forge::r-tidyverse=1.2.1
  - conda-forge::r-irkernel=1.1
  - conda-forge::r-cowplot=1.0.0
  - conda-forge::r-ggforce=0.3.1
  - pip:
    - pytz
    - python-dateutil
